---
version: 0.2
phases:


  pre_build:
      commands:
        - $(aws ecr get-login --no-include-email)  
        - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)


  build:
    commands:
      - docker build -t $ROLODEX_REPOSITORY_URI:$COMMIT_HASH .


  post_build:
    commands:
      - docker push $ROLODEX_REPOSITORY_URI:$COMMIT_HASH
      - printf '{"ImageURI":"%s:%s"}' $ROLODEX_REPOSITORY_URI $COMMIT_HASH > ImageDetail.json

artifacts:
  files:
    - ImageDetail.json
 